### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vasco3** [ArtskydJ/spell-check-cli#2]
Getting the following error when trying `spell hello`

```

# /usr/bin/spell: 1: /usr/bin/spell: Syntax error: "(" unexpected
```

**Comment by ArtskydJ** [comment]
Looks like it doesn't know to run with node. I think it needs the [shebang](https://en.wikipedia.org/wiki/Shebang_%28Unix%29).

**Comment by ArtskydJ** [comment]
I added a test for this in travis.

I needed a shebang, and LF (\n) line endings rather than CRLF (\r\n) line endings. Otherwise linux would look for a file called `node\r` which of course is ridiculous.
